INTERNAL_PORT=80
EXTERNAL_PORT=8080
HOST=http://10.28.11.49

docker run -p ${EXTERNAL_PORT}:${INTERNAL_PORT} -e CONFIGURATION_SWAGGER_PORT=${EXTERNAL_PORT} \
-e HOST=${HOST} -e CONFIGURATION_SWAGGER_PORT=${EXTERNAL_PORT} \
--name export-storage export_storage:latest &
