[template]
src = "production.tmpl"
dest = "/config/production.json"
keys = [
    "/configuration/logger/level",
    "/configuration/swagger/json/path",
    "/configuration/swagger/ui/path",
    "/configuration/db/type",
    "/configuration/db/host",
    "/configuration/db/port",
    "/configuration/db/username",
    "/configuration/db/password",
    "/configuration/db/database",
    "/configuration/db/synchronize",
    "/configuration/db/logging",
    "/configuration/search/default/page/size"
]
