[template]
src = "production.tmpl"
dest = "/config/production.json"
keys = [
    "/configuration/logger/level",
    "/configuration/swagger/json/path",
    "/configuration/swagger/ui/path",
    "/configuration/swagger/port",
    "/configuration/db/type",
    "/configuration/db/host",
    "/configuration/db/port",
    "/configuration/db/username",
    "/configuration/db/password",
    "/configuration/db/database",
    "/configuration/db/synchronize",
    "/configuration/db/logging",
    "/configuration/db/ssl/reject_unauthorized",
    "/configuration/db/ssl/ca",
    "/configuration/db/ssl/key",
    "/configuration/db/ssl/cert",
    "/configuration/search/default/page/size"
]
